# Generated by Django 5.1.5 on 2025-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('year_of_study', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
    ]
